
POST http://localhost:3000/student/grade
Content-Type: application/json

{
    "studentId":"BCS/27012/2201/DT",
    "subject":"biology",
    "grade":"40",
    "examType":"annual"
}

###
POST http://localhost:3000/subject/add
Content-Type: application/json

{
    "subject":"Displine",
    "subjectTeacher":"chacha bazaar"
}
